# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: protocol.proto
# Protobuf Python Version: 4.25.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x0eprotocol.proto\"\x12\n\x10ListFilesRequest\"\'\n\x11ListFilesResponse\x12\x12\n\nfile_names\x18\x01 \x03(\t2G\n\x0f\x44\x61taNodeService\x12\x34\n\tListFiles\x12\x11.ListFilesRequest\x1a\x12.ListFilesResponse\"\x00\x62\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'protocol_pb2', _globals)
if _descriptor._USE_C_DESCRIPTORS == False:
  DESCRIPTOR._options = None
  _globals['_LISTFILESREQUEST']._serialized_start=18
  _globals['_LISTFILESREQUEST']._serialized_end=36
  _globals['_LISTFILESRESPONSE']._serialized_start=38
  _globals['_LISTFILESRESPONSE']._serialized_end=77
  _globals['_DATANODESERVICE']._serialized_start=79
  _globals['_DATANODESERVICE']._serialized_end=150
# @@protoc_insertion_point(module_scope)
