# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: protocol.proto
# Protobuf Python Version: 4.25.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x0eprotocol.proto\"@\n\x15ReplicateChunkRequest\x12\x10\n\x08\x63hunk_id\x18\x01 \x01(\t\x12\x15\n\rchunk_content\x18\x02 \x01(\x0c\")\n\x16ReplicateChunkResponse\x12\x0f\n\x07success\x18\x01 \x01(\x08\"\x12\n\x10ListFilesRequest\"\'\n\x11ListFilesResponse\x12\x12\n\nfile_names\x18\x01 \x03(\t2\x8c\x01\n\x0f\x44\x61taNodeService\x12\x43\n\x0eReplicateChunk\x12\x16.ReplicateChunkRequest\x1a\x17.ReplicateChunkResponse\"\x00\x12\x34\n\tListFiles\x12\x11.ListFilesRequest\x1a\x12.ListFilesResponse\"\x00\x62\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'protocol_pb2', _globals)
if _descriptor._USE_C_DESCRIPTORS == False:
  DESCRIPTOR._options = None
  _globals['_REPLICATECHUNKREQUEST']._serialized_start=18
  _globals['_REPLICATECHUNKREQUEST']._serialized_end=82
  _globals['_REPLICATECHUNKRESPONSE']._serialized_start=84
  _globals['_REPLICATECHUNKRESPONSE']._serialized_end=125
  _globals['_LISTFILESREQUEST']._serialized_start=127
  _globals['_LISTFILESREQUEST']._serialized_end=145
  _globals['_LISTFILESRESPONSE']._serialized_start=147
  _globals['_LISTFILESRESPONSE']._serialized_end=186
  _globals['_DATANODESERVICE']._serialized_start=189
  _globals['_DATANODESERVICE']._serialized_end=329
# @@protoc_insertion_point(module_scope)
